=== hirah2205/ARINC-665/arinc665_xml/Arinc665MediaSet.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<schema
  targetNamespace="http://www.thomas-vogt.de/Arinc665MediaSet"
  elementFormDefault="qualified"
  xmlns="http://www.w3.org/2001/XMLSchema"
  xmlns:ams="http://www.thomas-vogt.de/Arinc665MediaSet" >

  <element name="MediaSet" type="ams:MediaSetType" >
    <annotation><documentation>
      Media Set Definition
    </documentation></annotation>
    <key name="FileKey" >
      <selector xpath="ams:RegularFile|ams:LoadFile|ams:BatchFile" />
      <field    xpath="@Name" />
    </key>
    <key name="LoadKey" >
      <selector xpath="ams:LoadFile" />
      <field    xpath="@Name" />
    </key>
    <key name="BatchKey" >
      <selector xpath="ams:BatchFile" />
      <field    xpath="@Name" />
    </key>
    <keyref name="FileRef" refer="ams:FileKey" >
      <selector xpath="ams:DataFile|ams:SupportFile" />
      <field    xpath="@NameRef" />
    </keyref>
    <keyref name="LoadRef" refer="ams:LoadKey" >
      <selector xpath="ams:Load" />
      <field    xpath="@NameRef" />
    </keyref>
    <keyref name="BatchRef" refer="ams:BatchKey" >
      <selector xpath="ams:Batch" />
      <field    xpath="@NameRef" />
    </keyref>
  </element>

  <element name="Medium"   type="ams:MediumType" >
  </element>

  <element name="Loads"    type="ams:LoadsType" />
  <element name="Load"     type="ams:LoadType" >
  </element>

  <element name="Batches"  type="ams:BatchesType" />
  <element name="Batch"    type="ams:BatchType" />

  <complexType name="MediaSetType" >
    <annotation><documentation>
      Media Set
    </documentation></annotation>
    <sequence>
      <element name="FilesUserDefinedData"   type="ams:UserDefinedDataType" minOccurs="0" maxOccurs="1" />
      <element name="LoadsUserDefinedData"   type="ams:UserDefinedDataType" minOccurs="0" maxOccurs="1" />
      <element name="BatchesUserDefinedData" type="ams:UserDefinedDataType" minOccurs="0" maxOccurs="1" />

      <element ref="ams:Medium"  minOccurs="1" maxOccurs="unbounded" />
      <element ref="ams:Loads"   minOccurs="1" maxOccurs="1" />
      <element ref="ams:Batches" minOccurs="0" maxOccurs="1" />
    </sequence>
    <attribute name="PartNumber"              type="ams:PartNumberType" use="required" />
    <attribute name="MediaSetCheckValue"      type="ams:CheckValueType" use="optional" />
    <attribute name="ListOfFilesCheckValue"   type="ams:CheckValueType" use="optional" />
    <attribute name="ListOfLoadsCheckValue"   type="ams:CheckValueType" use="optional" />
    <attribute name="ListOfBatchesCheckValue" type="ams:CheckValueType" use="optional" />
    <attribute name="FilesCheckValue"         type="ams:CheckValueType" use="optional" />
  </complexType>

  <complexType name="MediumType" >
    <annotation><documentation>
      Medium
    </documentation></annotation>
    <sequence>
      <group ref="ams:DirectoryFileGroup" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
  </complexType>

  <complexType name="FileType" abstract="true" >
    <annotation><documentation>
      Base of all Files
    </documentation></annotation>
    <attribute name="Name"       type="ams:NameType"       use="required" />
    <attribute name="CheckValue" type="ams:CheckValueType" use="optional" />
    <attribute name="SourcePath" type="string"             use="optional" />
  </complexType>

  <complexType name="RegularFileType" >
    <annotation><documentation>
      Regular Data File.
    </documentation></annotation>
    <complexContent>
      <restriction base="ams:FileType" >
        <attribute name="Name"       type="ams:NameType"       use="required" />
        <attribute name="CheckValue" type="ams:CheckValueType" use="optional" />
        <attribute name="SourcePath" type="string"             use="optional" />
      </restriction>
    </complexContent>
  </complexType>

  <complexType name="LoadFileType" >
    <annotation><documentation>
      Load Header File
    </documentation></annotation>
    <complexContent>
      <restriction base="ams:FileType" >
        <attribute name="Name"       type="ams:NameType"       use="required" />
        <attribute name="CheckValue" type="ams:CheckValueType" use="optional" />
        <attribute name="SourcePath" type="string"             use="optional" />
      </restriction>
    </complexContent>
  </complexType>

  <complexType name="BatchFileType" >
    <annotation><documentation>
      Batch File
    </documentation></annotation>
    <complexContent>
      <restriction base="ams:FileType" >
        <attribute name="Name"       type="ams:NameType"       use="required" />
        <attribute name="CheckValue" type="ams:CheckValueType" use="optional" />
        <attribute name="SourcePath" type="string"             use="optional" />
      </restriction>
    </complexContent>
  </complexType>

  <complexType name="DirectoryType" >
    <annotation><documentation>
      Directory within Medium.
    </documentation></annotation>
    <sequence>
      <group ref="ams:DirectoryFileGroup" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
    <attribute name="Name" type="ams:NameType" use="required" />
  </complexType>

  <complexType name="LoadsType" >
    <annotation><documentation>
      Loads Definition (all contained Loads)
    </documentation></annotation>
    <sequence>
      <element ref="ams:Load" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
  </complexType>

  <complexType name="LoadType" >
    <annotation><documentation>
      Load Definition
    </documentation></annotation>
    <sequence>
      <element name="TargetHardware"  type="ams:TargetHardwareType"  minOccurs="1" maxOccurs="unbounded" />
      <element name="DataFile"        type="ams:FileReferenceType"   minOccurs="0" maxOccurs="unbounded" />
      <element name="SupportFile"     type="ams:FileReferenceType"   minOccurs="0" maxOccurs="unbounded" />
      <element name="UserDefinedData" type="ams:UserDefinedDataType" minOccurs="0" maxOccurs="1" />
    </sequence>
    <attribute name="NameRef"     type="ams:NameRefType"    use="required" />
    <attribute name="PartNumber"  type="ams:PartNumberType" use="required" />
    <attribute name="PartFlags"   type="ams:HexValueType"   use="optional" default="0x0000" />
    <attribute name="Description" type="ams:StringType"     use="optional" />
    <attribute name="Type"        type="ams:HexValueType"   use="optional" default="0x0000" />
    <attribute name="LoadCheckValue"         type="ams:CheckValueType" use="optional" />
    <attribute name="DataFilesCheckValue"    type="ams:CheckValueType" use="optional" />
    <attribute name="SupportFilesCheckValue" type="ams:CheckValueType" use="optional" />
  </complexType>

  <complexType name="TargetHardwareType" >
    <annotation><documentation>
      Target Hardware Definition (Part of Load)
    </documentation></annotation>
    <sequence>
      <element name="Position" type="ams:PositionType" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
    <attribute name="ThwId" type="ams:TargetHardwareIdType" use="required" />
  </complexType>

  <complexType name="PositionType" >
    <annotation><documentation>
      Target Position Information (Part of Load)
    </documentation></annotation>
    <attribute name="Pos" type="ams:PosType" use="required" />
  </complexType>

  <complexType name="FileReferenceType" >
    <annotation><documentation>
      File Reference (part of Load)
    </documentation></annotation>
    <attribute name="NameRef"    type="ams:StringType"     use="required" />
    <attribute name="PartNumber" type="ams:PartNumberType" use="required" />
    <attribute name="CheckValue" type="ams:CheckValueType" use="optional" />
  </complexType>


  <complexType name="BatchesType" >
    <annotation><documentation>
      Batches Definition
    </documentation></annotation>
    <sequence>
      <element ref="ams:Batch" minOccurs="0" maxOccurs="unbounded" />
    </sequence>
  </complexType>

  <complexType name="BatchType" >
    <annotation><documentation>
      Batch Definition
    </documentation></annotation>
    <sequence>
      <element name="Target" type="ams:BatchTargetType" minOccurs="1" maxOccurs="unbounded" />
    </sequence>
    <attribute name="NameRef"    type="ams:NameRefType"    use="required" />
    <attribute name="PartNumber" type="ams:PartNumberType" use="required" />
    <attribute name="Comment"    type="ams:StringType"     use="optional" />
  </complexType>

  <complexType name="BatchTargetType" >
    <annotation><documentation>
      Batch Target Definition
    </documentation></annotation>
    <sequence>
      <element name="Load" type="ams:LoadReferenceType" minOccurs="1" maxOccurs="unbounded" />
    </sequence>
    <attribute name="ThwIdPos" type="ams:TargetHardwareIdPosType" use="required" />
  </complexType>

  <complexType name="LoadReferenceType" >
    <annotation><documentation>
      References a Load contained in the Media Set
    </documentation></annotation>
    <attribute name="NameRef" type="ams:NameRefType" use="required" />
  </complexType>

  <simpleType name="UserDefinedDataType" >
    <annotation><documentation>
      User Defined Data, which can be part of Load Files.
      Additionally, it can be added to File, Batches and Load Lists.
    </documentation></annotation>
    <restriction base="string" />
  </simpleType>

  <simpleType name="PartNumberType" >
    <annotation><documentation>
      Part Number of Media Set, Load, Batch, File
    </documentation></annotation>
    <restriction base="string" />
  </simpleType>

  <simpleType name="StringType" >
    <annotation><documentation>
      String
    </documentation></annotation>
    <restriction base="string" />
  </simpleType>

  <simpleType name="NameType" >
    <annotation><documentation>
      File Name
    </documentation></annotation>
    <restriction base="ams:StringType" >
    </restriction>
  </simpleType>

  <simpleType name="NameRefType" >
    <annotation><documentation>
      File Name Reference
    </documentation></annotation>
    <restriction base="ams:StringType" >
    </restriction>
  </simpleType>

  <simpleType name="TargetHardwareIdType" >
    <annotation><documentation>
      Target Hardware ID
    </documentation></annotation>
    <restriction base="string" />
  </simpleType>

  <simpleType name="PosType" >
    <annotation><documentation>
      Target Position
    </documentation></annotation>
    <restriction base="string" />
  </simpleType>

  <simpleType name="TargetHardwareIdPosType" >
    <annotation><documentation>
      Target Hardware ID - Position Information
    </documentation></annotation>
    <restriction base="string" />
  </simpleType>

  <simpleType name="CheckValueType" final="restriction" >
    <annotation><documentation>
      Valid Check Values.
      There is a difference between 'NotUsed' and omitted attribute.
      If no check value is given, the parent setting is used.
      With this handling a check value can be explicitly disabled again.
    </documentation></annotation>
    <restriction base="string" >
      <enumeration value="NotUsed" />
      <enumeration value="Crc8" />
      <enumeration value="Crc16" />
      <enumeration value="Crc32" />
      <enumeration value="Md5" />
      <enumeration value="Sha1" />
      <enumeration value="Sha256" />
      <enumeration value="Sha512" />
      <enumeration value="Crc64" />
    </restriction>
  </simpleType >

  <simpleType name="HexValueType" >
    <annotation><documentation>
      Hexadecimal Value
    </documentation></annotation>
    <restriction base="string" >
      <minLength value="3" />
      <pattern value="0x([0-9a-fA-F])+" />
    </restriction>
  </simpleType>

  <group name="DirectoryFileGroup" >
    <annotation>
      <documentation>Contents of media and directories</documentation>
    </annotation>
    <choice>
      <element name="Directory" type="ams:DirectoryType" />
      <element name="File"      type="ams:RegularFileType" />
      <element name="LoadFile"  type="ams:LoadFileType" />
      <element name="BatchFile" type="ams:BatchFileType" />
    </choice>
  </group>
</schema>

=== hirah2205/ARINC-665/test/ExampleMediaSet.xml
<?xml version="1.0" encoding="UTF-8" ?>

<MediaSet 
  xmlns="http://www.thomas-vogt.de/Arinc665MediaSet" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://www.thomas-vogt.de/Arinc665MediaSet ../arinc665_xml/Arinc665MediaSet.xsd"

  PartNumber="CCC" >

  <Medium>
    <File Name="File1" PartNumber="AABBCC1" SourcePath="File1" />
    <LoadFile Name="Load1.LUH" PartNumber="AABBCC" />
    <LoadFile Name="Load2.LUH" PartNumber="AABBDD" />
    <Directory Name="Directory1" >
      <File Name="File2" PartNumber="AABBCC2" SourcePath="File2" />
    </Directory>
    <File Name="Readme.txt" SourcePath="Readme.txt" />
    <BatchFile Name="Batch1.LUB" PartNumber="AABBEE" />
  </Medium>

  <Loads>
    <Load NameRef="Load1.LUH" Description="Test Description" >
      <TargetHardware ThwId="123456789ABCDEF" >
        <Position Pos="LEFT" />
        <Position Pos="RIGHT" />
      </TargetHardware>

      <DataFile    NameRef="File1" />
      <SupportFile NameRef="File2" />
    </Load>
    <Load NameRef="Load2.LUH" >
      <TargetHardware ThwId="123456789ABCDEF" />
      <TargetHardware ThwId="GHIJKLMNOPQRSTU" />

      <DataFile    NameRef="File1" />
      <SupportFile NameRef="File2" />
    </Load>
  </Loads>

  <Batches>
    <Batch NameRef="Batch1.LUB" Comment="Comment Text" >
      <Target ThwIdPos="123456789ABCDEF_RIGHT" >
        <Load NameRef="Load1.LUH" />
        <Load NameRef="Load2.LUH" />
      </Target>
    </Batch>
  </Batches>
</MediaSet>

=== hirah2205/ARINC-665/arinc665_xml/ExampleMediaSet.xml
<?xml version="1.0" encoding="UTF-8"?>
<MediaSet 
  xmlns="http://www.thomas-vogt.de/Arinc665MediaSet" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://www.thomas-vogt.de/Arinc665MediaSet Arinc665MediaSet.xsd"
  
  PartNumber="CCC" >
  
  <Medium>
    <File Name="File1" PartNumber="AABBCC1"/>
    <LoadFile Name="Load1" PartNumber="AABBCC" />
    <LoadFile Name="Load2" PartNumber="AABBDD" />
    <Directory Name="Directory1">
      <File Name="File2"  PartNumber="AABBCC2" />
    </Directory>
    <File Name="Readme.txt" />
    <BatchFile Name="Batch1" PartNumber="AABBEE" />
  </Medium>
  
  <Loads>
    <Load NameRef="Load1" Description="Test Description">
      <TargetHardware ThwId="123456789ABCDEF">
        <Position Pos="LEFT"/>
        <Position Pos="RIGHT"/>
      </TargetHardware>
      
      <DataFile    NameRef="File1" />
      <SupportFile NameRef="File2" />
    </Load>
    <Load NameRef="Load2">
      <TargetHardware ThwId="123456789ABCDEF" />
      <TargetHardware ThwId="GHIJKLMNOPQRSTU" />

      <DataFile    NameRef="File1" />
      <SupportFile NameRef="File2" />
    </Load>
  </Loads>
  
  <Batches>
    <Batch NameRef="Batch1" Comment="Comment Text" >
      <Target ThwIdPos="123456789ABCDEF_RIGHT">
        <Load NameRef="Load1" />
        <Load NameRef="Load2" />
      </Target>
    </Batch>
  </Batches>
</MediaSet>
